/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/aZKC62MBntB
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { IBM_Plex_Sans } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

ibm_plex_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import Image from "next/image"
import ButtonLink from "./ButtonLink"
import { PiFileHtmlThin , PiFileCssThin, PiFileTsxThin} from "react-icons/pi";
import { SiAdobephotoshop, SiAdobeillustrator , SiAdobecreativecloud, SiPm2, SiLetsencrypt, SiNginx} from "react-icons/si";
import { RiTailwindCssFill } from "react-icons/ri";
import { DiDocker } from "react-icons/di";
import { TbMailCog } from "react-icons/tb";

export function HomeGallery() {
  return (
    <div className="flex min-h-[100dvh] flex-col bg-background">
     <section className="container mx-auto flex flex-col items-center justify-center px-4 py-8 md:py-12 lg:py-16">
  <div className="max-w-3xl text-center">
    <h1 className="text-2xl font-bold tracking-tight text-foreground sm:text-3xl md:text-4xl lg:text-5xl">
      Welcome
    </h1>
    <p className="mt-4 text-lg text-muted-foreground">
      Discover a collection of digital media.
    </p>
    {/* <div className="mt-8 flex flex-wrap justify-center gap-4">
      <ButtonLink href="https://www.jp-gardening.com/" text="Websites" />
      <ButtonLink href="#" text="Custom Mailservers" />
      <ButtonLink href="#" text="Adobe Illustrations" />
      <ButtonLink href="#" text="Search Engine Optimization" />
    </div> */}
  </div>
</section>
<section id="websites" className="container mx-auto px-2 py-8 md:py-16">
  <h2 className="mb-8 text-3xl font-bold tracking-tight text-foreground text-center">Websites</h2>
  <div className="grid grid-cols-1 gap-8 sm:grid-cols-2 lg:grid-cols-3">
    {[
      {
        href: "https://www.jp-gardening.com/",
        title: "JP Gardening",
        description: "A simple but effective website for a local landscaping company.",
        imageSrc: "/jp_gardening.png",
        alt: "JP Gardening"
      },
      {
        href: "https://taxprep.vercel.app/",
        title: "Tax Preparation",
        description: "A website offering tax services with appointment setting and \"buy now\" functionality.",
        imageSrc: "/taxprep.png",
        alt: "Tax Prep"
      },
      {
        href: "localhost:3000",
        title: "Automotive Detailing",
        description: "A website showcasing automotive detailing services with appointment setting and \"buy now\" functionality.",
        imageSrc: "/DetailHabit.jpg",
        alt: "DetailHabit"
      }
    ].map((card, index) => (
      <div key={index} className="rounded-lg border border-input bg-card overflow-hidden shadow-sm transition-all hover:scale-105 hover:shadow-md flex flex-col h-full">
        <Link href={card.href} className="flex flex-col h-full">
          <div className="p-4 bg-black bg-opacity-50">
            <h3 className="mb-2 text-lg font-semibold text-white">{card.title}</h3>
            <p className="text-white text-sm">{card.description}</p>
          </div>
          <div className="relative flex-grow" style={{ paddingTop: '75%' }}> {/* 4:3 aspect ratio */}
            <Image
              src={card.imageSrc}
              alt={card.alt}
              layout="fill"
              objectFit="cover"
            />
          </div>
        </Link>
      </div>
    ))}
  </div>
</section>
     
      <section className="container mx-auto px-0 py-0 md:py-0">
        <h2 className="mb-8 text-3xl font-bold tracking-tight text-foreground"></h2>
        <div className="grid md:grid-cols-2 gap-8 sm:grid-cols-1 lg:grid-cols-3">
          <div className="rounded-lg border border-input bg-card p-4 shadow-sm">
            <h3 className="mb-2 text-lg text-center font-semibold text-foreground"> UI/UX Design  

            </h3>
             <div className="mx-auto pt-1 flex items-center justify-center flex-row space-x-4">
              
                <RiTailwindCssFill className="h-6 w-8 text-center text-primary"/>
                <PiFileTsxThin className="h-8 w-8 text-center text-primary"/>
                <PiFileCssThin className="h-8 w-8 text-center text-primary"/>
                <PiFileHtmlThin className="h-8 w-8 text-center text-primary"/>
                
              </div>
                <br></br>
                <div className="mx-auto px-6 text-justify">
                  <p className="text-xs">
                    We create seamless modern, responsive, and user-friendly experiences using the latest web technologies optimized for various devices and screen sizes.
                  </p>

                  <p className="text-xs">
                  We attract and form active client relationships by building beautiful user interfaces with exemplary application functionality.
                  </p> 
                </div>
          </div>
          <div className="rounded-lg border border-input bg-card p-4 shadow-sm">
            <h3 className="mb-2 text-lg text-center font-semibold text-foreground"> Graphic Design
          
            </h3>
            <div className="mx-auto pt-0.5 flex items-center justify-center flex-row space-x-4">
            <SiAdobeillustrator className="h-8 w-8 text-center text-primary" />
            <SiAdobecreativecloud className="h-8 w-8 text-center text-primary"/>
            <SiAdobephotoshop className="h-8 w-8 text-center text-primary"/>
            </div>
            <div className="mx-auto pt-6 px-6 text-justify">
             <p className="text-xs"> Graphics, color and typography are essential to visually representing your brand&apos;s identity and style. </p>
             <p className="text-xs"> Our excellence in graphic design comes from our meticulous blending of visual elements.</p>
          
             </div>
          </div>
          <div className="rounded-lg border border-input bg-card p-4 shadow-sm">
              <h3 className="mb-2 text-lg text-center font-semibold text-foreground"> Server Hosting Email & Security
              </h3>
            <div className="mx-auto flex items-center justify-center flex-row space-x-4">
              <SiNginx className="h-8 w-8 text-center text-primary" />
              
              
              <TbMailCog className="h-8 w-8 text-center text-primary"/>
              <SiLetsencrypt className="h-8 w-8 text-center text-primary"/>

              <DiDocker  className="h-11 w-11 text-center text-primary"/>
              <SiPm2  className="h-8 w-8 text-center text-primary"/> 
            </div>
            
            <div className="mx-auto pt-3 px-6 text-justify">
             <p className=" text-xs"
             > Protecting your communications and data is a prime objective in building and maintaining your server architecture.</p>
             <p className="text-xs"
             > Our websites use HTTPS, TLS 1.2+ , and ACME encryption protocols. Active firewall and port monitoring are also utilized in protecting you and your clients. </p>
            
          
             </div>
          </div>
        </div>
      
      </section>
      </div>
   
  )
}

function AccessibilityIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="16" cy="4" r="1" />
      <path d="m18 19 1-7-6 1" />
      <path d="m5 8 3-3 5.5 3-2.36 3.5" />
      <path d="M4.24 14.5a5 5 0 0 0 6.88 6" />
      <path d="M13.76 17.5a5 5 0 0 0-6.88-6" />
    </svg>
  )
}


function CodeIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="16 18 22 12 16 6" />
      <polyline points="8 6 2 12 8 18" />
    </svg>
  )
}


function TypeIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="4 7 4 4 20 4 20 7" />
      <line x1="9" x2="15" y1="20" y2="20" />
      <line x1="12" x2="12" y1="4" y2="20" />
    </svg>
  )
}


function XIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}

