/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/aZKC62MBntB
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { IBM_Plex_Sans } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

ibm_plex_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import Image from "next/image"
import ButtonLink from "./ButtonLink"
import { PiFileHtmlThin } from "react-icons/pi";

export function HomeGallery() {
  return (
    <div className="flex min-h-[100dvh] flex-col bg-background">
     <section className="container mx-auto flex flex-col items-center justify-center px-4 py-8 md:py-12 lg:py-16">
  <div className="max-w-3xl text-center">
    <h1 className="text-2xl font-bold tracking-tight text-foreground sm:text-3xl md:text-4xl lg:text-5xl">
      Welcome
    </h1>
    <p className="mt-4 text-lg text-muted-foreground">
      Discover a collection of digital media.
    </p>
    {/* <div className="mt-8 flex flex-wrap justify-center gap-4">
      <ButtonLink href="https://www.jp-gardening.com/" text="Websites" />
      <ButtonLink href="#" text="Custom Mailservers" />
      <ButtonLink href="#" text="Adobe Illustrations" />
      <ButtonLink href="#" text="Search Engine Optimization" />
    </div> */}
  </div>
</section>
<section id="websites" className="container mx-auto px-2 py-8 md:py-16">
  <h2 className="mb-8 text-3xl font-bold tracking-tight text-foreground text-center">Websites</h2>
  <div className="grid grid-cols-1 gap-8 sm:grid-cols-2 lg:grid-cols-3">
    {[
      {
        href: "https://www.jp-gardening.com/",
        title: "JP Gardening",
        description: "A simple but effective website for a local landscaping company.",
        imageSrc: "/jp_gardening.png",
        alt: "JP Gardening"
      },
      {
        href: "https://taxprep.vercel.app/",
        title: "Tax Preparation",
        description: "A website offering tax services with appointment setting and \"buy now\" functionality.",
        imageSrc: "/taxprep.png",
        alt: "Tax Prep"
      },
      {
        href: "localhost:3000",
        title: "Automotive Detailing",
        description: "A website showcasing automotive detailing services with appointment setting and \"buy now\" functionality.",
        imageSrc: "/DetailHabit.jpg",
        alt: "DetailHabit"
      }
    ].map((card, index) => (
      <div key={index} className="rounded-lg border border-input bg-card overflow-hidden shadow-sm transition-all hover:scale-105 hover:shadow-md flex flex-col h-full">
        <Link href={card.href} className="flex flex-col h-full">
          <div className="p-4 bg-black bg-opacity-50">
            <h3 className="mb-2 text-lg font-semibold text-white">{card.title}</h3>
            <p className="text-white text-sm">{card.description}</p>
          </div>
          <div className="relative flex-grow" style={{ paddingTop: '75%' }}> {/* 4:3 aspect ratio */}
            <Image
              src={card.imageSrc}
              alt={card.alt}
              layout="fill"
              objectFit="cover"
            />
          </div>
        </Link>
      </div>
    ))}
  </div>
</section>
     
      <section className="container mx-auto px-0 py-0 md:py-0">
        <h2 className="mb-8 text-3xl font-bold tracking-tight text-foreground"></h2>
        <div className="grid md:grid-cols-2 gap-8 sm:grid-cols-1 lg:grid-cols-4">
          <div className="rounded-lg border border-input bg-card p-4 shadow-sm">
          <PiFileHtmlThin /><CodeIcon className="mb-4 h-8 w-8 text-primary" />
            <h3 className="mb-2 text-lg font-semibold text-foreground"> UI/UX Design  </h3>
            <p className="text-muted-foreground">
             We create seamless modern, responsive, and user-friendly experiences using the latest web technologies optimized for various devices and screen sizes.
            </p>
           
          </div>
          <div className="rounded-lg border border-input bg-card p-4 shadow-sm">
          <TypeIcon className="mb-4 h-8 w-8 text-primary" />
          <h3 className="mb-2 text-lg font-semibold text-foreground"> Web Development </h3>
            <p className="text-muted-foreground">
            We accomplish this by building user interfaces, graphics, and application functionality; Attracting users and forming active client relationships.
          </p> 
          
          </div>
        </div>
      
      </section>
      </div>
   
  )
}

function AccessibilityIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="16" cy="4" r="1" />
      <path d="m18 19 1-7-6 1" />
      <path d="m5 8 3-3 5.5 3-2.36 3.5" />
      <path d="M4.24 14.5a5 5 0 0 0 6.88 6" />
      <path d="M13.76 17.5a5 5 0 0 0-6.88-6" />
    </svg>
  )
}


function CodeIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="16 18 22 12 16 6" />
      <polyline points="8 6 2 12 8 18" />
    </svg>
  )
}


function TypeIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="4 7 4 4 20 4 20 7" />
      <line x1="9" x2="15" y1="20" y2="20" />
      <line x1="12" x2="12" y1="4" y2="20" />
    </svg>
  )
}


function XIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}

